name: .NET Core

on:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: List build directory
      run: ls $Env:GITHUB_WORKSPACE\src\PointInTime.App\bin\Release\netcoreapp3.1\
